<?php
// Example: PHP arrays for stages and vehicles
$stages = [
  [1, 'Mahendra Highway', 'Road', 'Unlocked'],
  [2, 'Kathmandu City', 'Urban', 'Locked'],
  [3, 'Lumbini', 'Cultural', 'Locked'],
  [4, 'Pokhara', 'Lake Hill', 'Locked'],
  [5, 'Rara Lake', 'Snow + Lake', 'Locked'],
  [6, 'Nijgadh Fast Track', 'Speedway', 'Locked'],
  [7, 'Mustang Trail', 'Rocky', 'Locked'],
  [8, 'Everest Base Camp', 'Snowy Mountain', 'Locked'],
  [9, 'Terai Flatland', 'Smooth Drive', 'Locked'],
  [10, 'Chitwan National Park', 'Jungle Safari', 'Locked'],
  [11, 'Moon', 'Low Gravity', 'Bonus Locked'],
  [12, 'Mars Surface', 'Alien Planet', 'Locked'],
  [13, 'Cyber Arena', 'Futuristic', 'Locked'],
  [14, 'Space Highway', 'Sci-Fi', 'Locked'],
  [15, 'Glass Skyroad', 'Transparent Path', 'Locked'],
  [16, 'Gaindakot Bridge', 'Narrow Bridges', 'Locked'],
  [17, 'Boudhanath Circuit', 'Cultural', 'Locked'],
  [18, 'Pashupatinath Round', 'Religious Temple', 'Locked'],
  [19, 'Jungle Trail', 'Forest Track', 'Locked'],
  [20, 'Flood Survival', 'Disaster Stage', 'Locked'],
  [21, 'Earthquake Ruins', 'Broken Terrain', 'Locked'],
  [22, 'Snowstorm Drive', 'Icy Road', 'Locked'],
  [23, 'AI Robot War Zone', 'Battle Area', 'Locked'],
  [24, 'Neon City', 'Lit-Up Roads', 'Locked'],
  [25, 'Junkyard Rush', 'Scrap Terrain', 'Locked'],
  [26, 'Alien Planet', 'Floating Gravity', 'Locked'],
  [27, 'Desert Sandstorm', 'Windy, Dry', 'Locked'],
  [28, 'Thamel Night Drive', 'Crowded Market', 'Locked'],
  [29, 'Bhaktapur Durbar Square', 'Ancient', 'Locked'],
  [30, 'Fewa Tal', 'Lakeside Beauty', 'Locked'],
  [31, 'Hidden Tunnel (secret stage)', 'Secret Bonus', 'Hidden Bonus']
];
$vehicles = [
  [1, 'Rickshaw', 'Local', 'Unlocked'],
  [2, 'Brawan Jeep', 'Offroad', 'Unlocked'],
  [3, 'Hot Rod', 'Classic Race', 'Locked'],
  [4, 'Tractor', 'Farming', 'Locked'],
  [5, 'Police Van', 'Official', 'Locked'],
  [6, 'Ambulance', 'Emergency', 'Locked'],
  [7, 'School Bus', 'Public Transport', 'Locked'],
  [8, 'Moonlander', 'Sci-Fi', 'Bonus Locked'],
  [9, 'Helicopter', 'Air Vehicle', 'Locked'],
  [10, 'Cycle', 'Simple', 'Unlocked'],
  [11, 'Bike', 'Motor', 'Locked'],
  [12, 'Fire Truck', 'Emergency', 'Locked'],
  [13, 'Electric Car', 'Modern', 'Locked'],
  [14, 'Tuk Tuk', 'Local Taxi', 'Locked'],
  [15, 'Bullock Cart', 'Traditional', 'Locked'],
  [16, 'Army Truck', 'Military', 'Locked'],
  [17, 'Drone Rider', 'Futuristic', 'Locked'],
  [18, 'Solar Car', 'Sci-Fi', 'Locked'],
  [19, 'Gravity Bike', 'Low Gravity', 'Locked'],
  [20, 'Magnet Truck', 'High Tech', 'Locked'],
  [21, 'Luxury SUV', 'Premium', 'Locked'],
  [22, 'Transformer Ride', 'Morphing', 'Locked'],
  [23, 'AI Car', 'Robot Driven', 'Locked'],
  [24, 'Cargo Truck', 'Heavy Vehicle', 'Locked'],
  [25, 'Van', 'Delivery', 'Locked'],
  [26, 'Vintage Car', 'Classic', 'Locked'],
  [27, 'Snowmobile', 'Ice Terrain', 'Locked'],
  [28, 'Jet Car', 'Super Speed', 'Locked'],
  [29, 'Electric Scooter', 'Light Ride', 'Locked'],
  [30, 'Horse Cart', 'Traditional Rural', 'Locked'],
  [31, 'UFO Car (hidden)', 'Alien Ride', 'Hidden Bonus']
];
// Data arrays for use in PHP backend or AJAX. No browser-side effect unless used in PHP-rendered HTML/JS.
?>
