const VEHICLE_LIST = [
  { name: "Jeep", type: "Offroad", status: "Unlocked", speed: 10, grip: 8, fuelEfficiency: 7, suspension: 6, unlockCost: 0 },
  { name: "Tractor", type: "Farming", status: "Unlocked", speed: 5, grip: 10, fuelEfficiency: 9, suspension: 8, unlockCost: 0 },
  { name: "Rocket", type: "Super Speed", status: "Locked", speed: 20, grip: 5, fuelEfficiency: 3, suspension: 4, unlockCost: 100 },
  { name: "Bus", type: "Public Transport", status: "Unlocked", speed: 7, grip: 7, fuelEfficiency: 6, suspension: 7, unlockCost: 0 },
  { name: "Helicopter", type: "Air Vehicle", status: "Locked", speed: 15, grip: 9, fuelEfficiency: 5, suspension: 10, unlockCost: 150 },
  { name: "Rickshaw", type: "Local", status: "Unlocked", speed: 6, grip: 7, fuelEfficiency: 8, suspension: 5, unlockCost: 0 },
  { name: "Brawan Jeep", type: "Offroad", status: "Unlocked", speed: 9, grip: 8, fuelEfficiency: 7, suspension: 6, unlockCost: 0 },
  { name: "Hot Rod", type: "Classic Race", status: "Locked", speed: 14, grip: 6, fuelEfficiency: 5, suspension: 5, unlockCost: 120 },
  { name: "Police Van", type: "Official", status: "Locked", speed: 8, grip: 7, fuelEfficiency: 6, suspension: 7, unlockCost: 130 },
  { name: "Ambulance", type: "Emergency", status: "Locked", speed: 9, grip: 7, fuelEfficiency: 6, suspension: 7, unlockCost: 140 },
  { name: "School Bus", type: "Public Transport", status: "Locked", speed: 6, grip: 7, fuelEfficiency: 6, suspension: 7, unlockCost: 110 },
  { name: "Moonlander", type: "Sci-Fi", status: "Bonus Locked", speed: 12, grip: 8, fuelEfficiency: 7, suspension: 9, unlockCost: 200 },
  { name: "Cycle", type: "Simple", status: "Unlocked", speed: 4, grip: 6, fuelEfficiency: 10, suspension: 3, unlockCost: 0 },
  { name: "Bike", type: "Motor", status: "Locked", speed: 11, grip: 7, fuelEfficiency: 7, suspension: 4, unlockCost: 90 },
  { name: "Fire Truck", type: "Emergency", status: "Locked", speed: 7, grip: 7, fuelEfficiency: 5, suspension: 6, unlockCost: 100 },
  { name: "Electric Car", type: "Modern", status: "Locked", speed: 13, grip: 8, fuelEfficiency: 9, suspension: 7, unlockCost: 150 },
  { name: "Tuk Tuk", type: "Local Taxi", status: "Locked", speed: 6, grip: 7, fuelEfficiency: 8, suspension: 5, unlockCost: 80 },
  { name: "Bullock Cart", type: "Traditional", status: "Locked", speed: 3, grip: 9, fuelEfficiency: 10, suspension: 4, unlockCost: 70 },
  { name: "Army Truck", type: "Military", status: "Locked", speed: 8, grip: 8, fuelEfficiency: 6, suspension: 7, unlockCost: 130 },
  { name: "Drone Rider", type: "Futuristic", status: "Locked", speed: 16, grip: 9, fuelEfficiency: 5, suspension: 8, unlockCost: 160 },
  { name: "Solar Car", type: "Sci-Fi", status: "Locked", speed: 14, grip: 8, fuelEfficiency: 10, suspension: 7, unlockCost: 140 },
  { name: "Gravity Bike", type: "Low Gravity", status: "Locked", speed: 15, grip: 7, fuelEfficiency: 6, suspension: 6, unlockCost: 150 },
  { name: "Magnet Truck", type: "High Tech", status: "Locked", speed: 9, grip: 9, fuelEfficiency: 7, suspension: 7, unlockCost: 120 },
  { name: "Luxury SUV", type: "Premium", status: "Locked", speed: 12, grip: 8, fuelEfficiency: 7, suspension: 8, unlockCost: 130 },
  { name: "Transformer Ride", type: "Morphing", status: "Locked", speed: 14, grip: 8, fuelEfficiency: 6, suspension: 7, unlockCost: 140 },
  { name: "AI Car", type: "Robot Driven", status: "Locked", speed: 15, grip: 9, fuelEfficiency: 7, suspension: 8, unlockCost: 150 },
  { name: "Cargo Truck", type: "Heavy Vehicle", status: "Locked", speed: 7, grip: 8, fuelEfficiency: 6, suspension: 7, unlockCost: 110 },
  { name: "Van", type: "Delivery", status: "Locked", speed: 8, grip: 7, fuelEfficiency: 7, suspension: 6, unlockCost: 100 },
  { name: "Vintage Car", type: "Classic", status: "Locked", speed: 10, grip: 7, fuelEfficiency: 6, suspension: 6, unlockCost: 90 },
  { name: "Snowmobile", type: "Ice Terrain", status: "Locked", speed: 11, grip: 8, fuelEfficiency: 5, suspension: 7, unlockCost: 120 },
  { name: "Jet Car", type: "Super Speed", status: "Locked", speed: 20, grip: 6, fuelEfficiency: 4, suspension: 5, unlockCost: 130 },
  { name: "Electric Scooter", type: "Light Ride", status: "Locked", speed: 9, grip: 7, fuelEfficiency: 9, suspension: 5, unlockCost: 110 },
  { name: "Horse Cart", type: "Traditional Rural", status: "Locked", speed: 4, grip: 9, fuelEfficiency: 10, suspension: 4, unlockCost: 80 },
  { name: "UFO Car (hidden)", type: "Alien Ride", status: "Hidden Bonus", speed: 18, grip: 8, fuelEfficiency: 6, suspension: 7, unlockCost: 0 },
  { name: "Snow Truck", type: "Ice Terrain", status: "Locked", speed: 8, grip: 8, fuelEfficiency: 6, suspension: 7, unlockCost: 120 },
  { name: "Mountain Bike", type: "Offroad", status: "Unlocked", speed: 9, grip: 9, fuelEfficiency: 8, suspension: 6, unlockCost: 0 },
  { name: "Electric ATV", type: "Offroad", status: "Locked", speed: 12, grip: 8, fuelEfficiency: 9, suspension: 7, unlockCost: 130 },
  { name: "Hover Car", type: "Futuristic", status: "Locked", speed: 16, grip: 9, fuelEfficiency: 7, suspension: 8, unlockCost: 140 },
  { name: "Speedster", type: "Race", status: "Locked", speed: 18, grip: 7, fuelEfficiency: 5, suspension: 6, unlockCost: 150 },
  { name: "Mini Truck", type: "Delivery", status: "Unlocked", speed: 7, grip: 7, fuelEfficiency: 7, suspension: 6, unlockCost: 0 },
  { name: "Electric Bike", type: "Motor", status: "Locked", speed: 13, grip: 8, fuelEfficiency: 9, suspension: 5, unlockCost: 120 },
  { name: "Classic Convertible", type: "Classic", status: "Locked", unlockCost: 100 },
  { name: "Fire Bike", type: "Emergency", status: "Locked", unlockCost: 110 },
  { name: "Police Bike", type: "Official", status: "Locked", unlockCost: 120 },
  { name: "Luxury Sedan", type: "Premium", status: "Locked", unlockCost: 130 },
  { name: "Cargo Van", type: "Delivery", status: "Locked", unlockCost: 110 },
  { name: "Snowmobile Deluxe", type: "Ice Terrain", status: "Locked", unlockCost: 140 },
  { name: "Rocket Bike", type: "Super Speed", status: "Locked", unlockCost: 150 },
  { name: "Alien Hover", type: "Alien Ride", status: "Hidden Bonus", unlockCost: 0 },
];

// Export for use in other modules
if (typeof module !== 'undefined') module.exports = VEHICLE_LIST;
export default VEHICLE_LIST;
